### PR TITLE
Complete Website Navigation

### PR DESCRIPTION
**Pull request by Botlhale-Setou**
**Tasks done**
- Fix linters
- Website navigation

### CODE REVIEW

**Review by codepantha — CHANGES_REQUESTED** [review]
# STATUS: REQUIRES CHANGES ♻️ 

## Hi team 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🎯 
✔️ Descriptive PR
✔️ Followed wireframe design
✔️ App working exactly as expected
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

- [x] The live demo link in your README doesn't work. Please remove it or replace it with a "Coming Soon..." text if your application is not live yet 👍 
- [x] I noticed that the MIT license link in your README is broken. Please try to fix it 🙏 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Botlhale-Setou** [comment]
**Changes implemented**
- Replace dummy live link in README.md with "coming soon..."
- Fix README.md link to MIT.md

**Review by KDlamini — CHANGES_REQUESTED** [review]
### Hi team @Botlhale-Setou, @Khaled-AlKhateeb 🙋‍♀️,  

There are still some changes requested by the previous reviewer that aren't addressed yet. You are almost there! 💪🏾 

## Required Changes ♻️
 
- You only commented that you implemented the required changes but didn't actually push any changes on your branch 🤷🏾‍♂️ 
- Please make sure that the committed changes are pushed and visible on your GitHub branch.

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Botlhale-Setou** [comment]
@KDlamini All issues are resolved now 😄

**Review by peterrobert — APPROVED** [review]
Hi @Botlhale-Setou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
